### ISSUE TITLE
希望能提供Eigen版本

### ISSUE THREAD

**Issue by yucong-zhang** [mpt0816/Cilqr#1]
在ubuntu18.04环境中安装ros_melodic后克隆了该工程后进行catkin_make 过程中报错 如下`/home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/ilqr_optimizer.cc: In member function ‘void planning::IlqrOptimizer::DynamicsConsJacbian(const State&, const Control&, planning::State*, planning::Control*)’:
/home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/ilqr_optimizer.cc:660:88: error: no matching function for call to ‘planning::RelaxBarrierFunction<6>::Jacbian(double, <brace-enclosed initializer list>)’
   *cost_Jx += state_barrier_.Jacbian(0.0 - state(3, 0), {0.0, 0.0, 0.0, -1.0, 0.0, 0.0}) +
                                                                                        ^
In file included from /home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/ilqr_optimizer.h:9:0,
                 from /home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/ilqr_optimizer.cc:2:
/home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/barrier_function.h:115:31: note: candidate: Eigen::Matrix<double, N, 1> planning::RelaxBarrierFunction<N>::Jacbian(double, const Eigen::Matrix<double, N, 1>&) [with long unsigned int N = 6]
   Eigen::Matrix<double, N, 1> Jacbian(
                               ^~~~~~~
/home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/barrier_function.h:115:31: note:   no known conversion for argument 2 from ‘<brace-enclosed initializer list>’ to ‘const Eigen::Matrix<double, 6, 1>&’
/home/zyc/ros_ws/src/Cilqr/algorithm/ilqr/ilqr_optimizer.cc:661:111: error: no matching function for call to ‘planning::RelaxBarrierFunction<6>::Jacbian(double, <brace-enclosed initializer list>)’
 te_barrier_.Jacbian(state(3, 0) - vehicle_param_.max_velocity, {0.0, 0.0, 0.0, 1.0, 0.0, 0.0}) +`

**Comment by mpt0816** [comment]
3.4.0
